name: Check

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.m2
          ~/.android/build-cache
        key: ${GITHUB_REF##*/}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Check with gradle
      run: ./gradlew test
